name: Rust

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            test_skips: ""
          - os: ubuntu-latest
            test_skips: "-- --skip expected::panics::TestPanic_IO"
          - os: macos-latest
            test_skips: "-- --skip expected::panics::TestPanic_IO"
    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo clean -p fn-fixture && cargo test --verbose ${{ matrix.test_skips }}
